# Generated by Django 4.2.2 on 2023-06-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
