version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.staging
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/core/staticfiles
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - media_volume:/app/media
      - static_volume:/app/core/staticfiles
    depends_on:
      - backend
volumes:
  media_volume:
  static_volume: