version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.staging
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - .:/app
      - media_volume:/app/media
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - media_volume:/app/media
    depends_on:
      - backend
volumes:
  media_volume: