# Generated by Django 4.2.2 on 2023-06-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='sender',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='properties',
            name='points_given',
            field=models.CharField(choices=[('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50')], default='10', max_length=3),
        ),
    ]
