# Generated by Django 4.2.2 on 2023-06-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='gif',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='photos/user_form'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='react_by',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
