# Generated by Django 4.2.2 on 2023-07-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_comments_created_alter_comments_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='parent_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
