# Generated by Django 4.2.2 on 2023-07-19 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_posts_parent_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
