# Generated by Django 4.2.2 on 2023-07-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='react_by',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
