# Generated by Django 4.2.2 on 2023-07-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_posts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('-created', 'active'), 'verbose_name': 'posts', 'verbose_name_plural': 'posts'},
        ),
    ]
