# Generated by Django 4.2.2 on 2023-07-26 17:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0010_reaction_userreaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userreaction',
            unique_together={('created_by', 'object_id', 'content_type')},
        ),
    ]
