# Generated by Django 4.2.2 on 2023-07-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_userpoints_delete_recognition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userpoints',
        ),
    ]
