# Generated by Django 4.2.2 on 2023-07-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_comment_remove_transaction_react_by_delete_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='userreaction',
            options={'ordering': ('-created',)},
        ),
    ]
