# Generated by Django 4.2.2 on 2023-07-21 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_userpoints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpoints',
            options={'verbose_name': 'userpoints', 'verbose_name_plural': 'userpoints'},
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
